version: '3'

services:
  backend:
    build:
      context: .
      args:
        DATABASE_URL: mysql://hash_storage:gooriruc2Al4eeSh@172.17.0.1:3306/hash_storage
    restart: always
    ports:
      - "60001:8000"
